# GitHub Actions Workflow: Update URLsToGo Preview Link
#
# This workflow automatically updates a URLsToGo shortlink when a preview deployment completes.
# Works with Vercel, Cloudflare Pages, and GitHub Pages.
#
# Setup Instructions:
# 1. Copy this file to your project repo: .github/workflows/update-preview-link.yml
# 2. Add these GitHub Secrets to your repo (Settings → Secrets → Actions):
#    - URLSTOGO_API_KEY: Your URLsToGo API key (create at go.urlstogo.cloud/admin → API Keys)
# 3. Customize the env variables below if needed (repo name, platform, etc.)
#
# The shortlink will be: go.urlstogo.cloud/{repo-name}--preview

name: Update Preview Link

on:
  # Trigger on any push to preview branches (not main, since that's typically production)
  push:
    branches:
      - preview
      - staging
      - 'preview/**'
      - 'feat/**'

  # Also trigger when deployments complete (works with Vercel, Cloudflare, etc.)
  deployment_status:

  # Allow manual trigger for testing
  workflow_dispatch:

env:
  # REQUIRED: Repository name (auto-detected, or customize if needed)
  REPO_NAME: ${{ github.event.repository.name }}

  # REQUIRED: Your URLsToGo domain
  URLSTOGO_DOMAIN: go.urlstogo.cloud

  # OPTIONAL: Set deployment platform (auto-detects if not set)
  # Options: vercel, cloudflare-pages, github-pages
  DEPLOYMENT_PLATFORM: auto

  # OPTIONAL: Override Cloudflare Pages project name (defaults to repo name)
  # Only needed if your CF Pages project name differs from your repo name
  # CF_PROJECT_NAME: my-custom-project

jobs:
  update-preview-link:
    name: Update Preview Link
    runs-on: ubuntu-latest

    # Only run on successful deployments or direct push events
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success') ||
      github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect deployment URL
        id: detect-url
        env:
          # Pass GitHub context as environment variables (safer than direct interpolation)
          GH_REF_NAME: ${{ github.ref_name }}
          GH_REPO_NAME: ${{ github.event.repository.name }}
          GH_REPO_OWNER: ${{ github.repository_owner }}
          GH_EVENT_NAME: ${{ github.event_name }}
          GH_DEPLOYMENT_URL: ${{ github.event.deployment_status.environment_url }}
          PLATFORM: ${{ env.DEPLOYMENT_PLATFORM }}
          CF_PROJECT_OVERRIDE: ${{ env.CF_PROJECT_NAME }}
        run: |
          set -euo pipefail  # Exit on error, undefined vars, pipe failures

          DEPLOYMENT_URL=""

          # Auto-detect platform if not specified
          if [ "$PLATFORM" = "auto" ]; then
            if [ -f "vercel.json" ] || [ -f ".vercel/project.json" ]; then
              PLATFORM="vercel"
            elif [ -f "wrangler.toml" ]; then
              PLATFORM="cloudflare-pages"
            elif [ -f ".github/workflows/pages.yml" ] || [ -f ".github/workflows/deploy-pages.yml" ]; then
              PLATFORM="github-pages"
            fi
          fi

          echo "Detected platform: $PLATFORM"

          # Slugify function (mimics Vercel/Cloudflare slugification)
          # Input is passed via stdin to avoid command substitution
          slugify() {
            # Read from stdin, convert to lowercase, replace non-alphanumeric with hyphens
            tr '[:upper:]' '[:lower:]' | \
              sed 's/[^a-z0-9-]/-/g' | \
              sed 's/--*/-/g' | \
              sed 's/^-//' | \
              sed 's/-$//'
          }

          # Get deployment URL based on platform
          case "$PLATFORM" in
            vercel)
              # For Vercel: Use deployment URL from environment or construct from branch
              if [ "$GH_EVENT_NAME" = "deployment_status" ] && [ -n "$GH_DEPLOYMENT_URL" ]; then
                DEPLOYMENT_URL="$GH_DEPLOYMENT_URL"
              else
                # Slugify repo name, branch name, and owner (using stdin to prevent injection)
                REPO_SLUG=$(echo "$GH_REPO_NAME" | slugify)
                BRANCH_SLUG=$(echo "$GH_REF_NAME" | slugify)
                OWNER_SLUG=$(echo "$GH_REPO_OWNER" | slugify)

                DEPLOYMENT_URL="https://${REPO_SLUG}-git-${BRANCH_SLUG}-${OWNER_SLUG}.vercel.app"
              fi
              ;;

            cloudflare-pages)
              # For Cloudflare Pages: Use custom project name or default to repo name
              if [ -n "$CF_PROJECT_OVERRIDE" ]; then
                CF_PROJECT=$(echo "$CF_PROJECT_OVERRIDE" | slugify)
              else
                CF_PROJECT=$(echo "$GH_REPO_NAME" | slugify)
              fi

              BRANCH_SLUG=$(echo "$GH_REF_NAME" | slugify)
              DEPLOYMENT_URL="https://${BRANCH_SLUG}.${CF_PROJECT}.pages.dev"
              ;;

            github-pages)
              # For GitHub Pages: Use repository URL
              OWNER_SLUG=$(echo "$GH_REPO_OWNER" | slugify)
              REPO_SLUG=$(echo "$GH_REPO_NAME" | slugify)
              DEPLOYMENT_URL="https://${OWNER_SLUG}.github.io/${REPO_SLUG}"
              ;;

            *)
              echo "❌ Could not detect deployment platform. Please set DEPLOYMENT_PLATFORM env var."
              exit 1
              ;;
          esac

          if [ -z "$DEPLOYMENT_URL" ]; then
            echo "❌ Could not determine deployment URL"
            exit 1
          fi

          echo "Deployment URL: $DEPLOYMENT_URL"
          # Use >> $GITHUB_OUTPUT (secure) instead of echo with command substitution
          {
            echo "url=$DEPLOYMENT_URL"
            echo "platform=$PLATFORM"
          } >> "$GITHUB_OUTPUT"

      - name: Update URLsToGo preview link
        env:
          URLSTOGO_API_KEY: ${{ secrets.URLSTOGO_API_KEY }}
          PREVIEW_CODE: ${{ github.event.repository.name }}--preview
          DEPLOYMENT_URL: ${{ steps.detect-url.outputs.url }}
          PLATFORM: ${{ steps.detect-url.outputs.platform }}
        run: |
          set -euo pipefail  # Exit on error, undefined vars, pipe failures

          echo "📝 Updating preview link: $URLSTOGO_DOMAIN/${PREVIEW_CODE}"
          echo "🎯 Target URL: $DEPLOYMENT_URL"

          # Call URLsToGo API to create/update preview link
          # Use printf to safely format JSON (prevents injection)
          RESPONSE=$(curl -s -w "\n%{http_code}" \
            -X PUT \
            -H "Authorization: Bearer $URLSTOGO_API_KEY" \
            -H "Content-Type: application/json" \
            --data "$(printf '{"destination":"%s"}' "$DEPLOYMENT_URL")" \
            "https://${URLSTOGO_DOMAIN}/api/preview-links/${PREVIEW_CODE}")

          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          BODY=$(echo "$RESPONSE" | head -n-1)

          if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]; then
            echo "✅ Preview link updated successfully!"
            echo ""
            echo "🔗 Preview link: https://${URLSTOGO_DOMAIN}/${PREVIEW_CODE}"
            echo "🌐 Platform: $PLATFORM"
            echo "📦 Deployment: $DEPLOYMENT_URL"
            echo ""
            echo "Response: $BODY"
          else
            echo "❌ Failed to update preview link (HTTP $HTTP_CODE)"
            echo "Response: $BODY"
            exit 1
          fi
